### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by mits87** [westlakedesign/automatic_record#1]
Hello, 

I have Rails5 project and I would like use your GEM but the GEM isn't compatible with this version of Rails. Is there any chance to upgrade your GEM to latest version of Rails?

Best Regards
Peter

**Comment by gregawoods** [comment]
Resolved by https://github.com/westlakedesign/automatic_record/commit/673f323ac947c51831b7be982bf6be65e0c56dbc

Thanks!
